import type { DashboardStats, Lead } from "./types"

export const sampleLeads: Lead[] = [
  {
    id: 1,
    name: "Rajesh Kumar",
    company: "TechVision India Pvt Ltd",
    title: "CTO",
    email: "rajesh.kumar@techvision.in",
    phone: "+91 98765 43210",
    status: "New",
    priority: "High",
    assignedTo: "Priya Sharma",
    lastContact: "2024-01-25",
    source: "Website",
    campaign: "Q1 Digital Campaign",
    linkedIn: "linkedin.com/in/rajesh-kumar",
    website: "techvision.in",
    address: "Koramangala, Bangalore",
    notes: ["Initial meeting scheduled for next week", "Interested in SUV models"],
    activities: [
      {
        id: 1,
        type: "Email",
        description: "Sent introduction email",
        date: "2024-01-25",
        performedBy: "Priya Sharma",
      },
      {
        id: 2,
        type: "Call",
        description: "Discussed SUV options",
        date: "2024-01-27",
        performedBy: "Amit Patel",
      },
    ],
    carModel: "SUV X1",
    preferredBudget: "₹30-40 lakhs",
    testDriveDate: "2024-02-05",
  },
  {
    id: 2,
    name: "Anita Desai",
    company: "GlobalServe Solutions",
    title: "CEO",
    email: "anita.d@globalserve.co.in",
    phone: "+91 99999 88888",
    status: "Qualified",
    priority: "Medium",
    assignedTo: "Amit Patel",
    lastContact: "2024-01-24",
    source: "LinkedIn",
    linkedIn: "linkedin.com/in/anita-desai",
    website: "globalserve.co.in",
    address: "Cyber City, Gurugram",
    notes: ["Looking for luxury sedan", "Budget approved for Q1"],
    activities: [
      {
        id: 3,
        type: "LinkedIn",
        description: "Connected on LinkedIn",
        date: "2024-01-20",
        performedBy: "Amit Patel",
      },
      {
        id: 4,
        type: "Email",
        description: "Sent brochure for Sedan Y2",
        date: "2024-01-22",
        performedBy: "Amit Patel",
      },
    ],
    carModel: "Sedan Y2",
    preferredBudget: "₹40-50 lakhs",
    testDriveDate: "2024-02-10",
  },
  {
    id: 3,
    name: "Suresh Menon",
    company: "Innovate Retail Ltd",
    title: "Head of Operations",
    email: "suresh.m@innovateretail.in",
    phone: "+91 98765 12345",
    status: "Contacted",
    priority: "Low",
    assignedTo: "Priya Sharma",
    lastContact: "2024-01-23",
    source: "Trade Show",
    campaign: "Auto Expo 2024",
    website: "innovateretail.in",
    address: "Anna Nagar, Chennai",
    notes: ["Interested in fleet purchase", "Prefers fuel-efficient models"],
    activities: [
      {
        id: 5,
        type: "Trade Show",
        description: "Met at Auto Expo 2024",
        date: "2024-01-15",
        performedBy: "Rahul Kapoor",
      },
      {
        id: 6,
        type: "Call",
        description: "Discussed fleet options",
        date: "2024-01-23",
        performedBy: "Priya Sharma",
      },
    ],
    carModel: "Hatchback Z3",
    preferredBudget: "₹15-20 lakhs per vehicle",
    testDriveDate: "2024-02-15",
  },
  {
    id: 4,
    name: "Vikram Singh",
    company: "Singh Enterprises",
    title: "Owner",
    email: "vikram@singhenterprises.com",
    phone: "+91 98765 67890",
    status: "Proposal",
    priority: "High",
    assignedTo: "Neha Gupta",
    lastContact: "2024-01-28",
    source: "Referral",
    address: "Civil Lines, New Delhi",
    notes: ["Interested in luxury SUV", "Wants customization options"],
    activities: [
      {
        id: 7,
        type: "Referral",
        description: "Referred by existing customer Rajesh Kumar",
        date: "2024-01-20",
        performedBy: "System",
      },
      {
        id: 8,
        type: "Meeting",
        description: "In-person meeting at showroom",
        date: "2024-01-28",
        performedBy: "Neha Gupta",
      },
    ],
    carModel: "Luxury SUV X5",
    preferredBudget: "₹70-80 lakhs",
    testDriveDate: "2024-02-02",
  },
  {
    id: 5,
    name: "Priya Reddy",
    company: "Reddy Pharmaceuticals",
    title: "CFO",
    email: "priya.r@reddypharma.com",
    phone: "+91 99999 55555",
    status: "Won",
    priority: "Medium",
    assignedTo: "Amit Patel",
    lastContact: "2024-01-30",
    source: "Website",
    campaign: "Year-End Sale",
    website: "reddypharma.com",
    address: "Jubilee Hills, Hyderabad",
    notes: ["Purchased Sedan Y2", "Interested in service package"],
    activities: [
      {
        id: 9,
        type: "Website",
        description: "Submitted inquiry form",
        date: "2024-01-10",
        performedBy: "System",
      },
      {
        id: 10,
        type: "Email",
        description: "Sent quote for Sedan Y2",
        date: "2024-01-15",
        performedBy: "Amit Patel",
      },
      {
        id: 11,
        type: "Sale",
        description: "Finalized Sedan Y2 purchase",
        date: "2024-01-30",
        performedBy: "Amit Patel",
      },
    ],
    carModel: "Sedan Y2",
    preferredBudget: "₹45 lakhs",
    testDriveDate: "2024-01-20",
  },
]

export const sampleStats: DashboardStats = {
  totalLeads: 2420,
  newLeads: {
    daily: 45,
    weekly: 280,
    monthly: 1200,
  },
  qualifiedLeads: 854,
  conversionRate: 35.2,
  leadsByStatus: {
    New: 500,
    Contacted: 800,
    Qualified: 600,
    Proposal: 300,
    Won: 150,
    Lost: 70,
  },
  leadsBySource: {
    Website: 800,
    Facebook: 600,
    "Google Ads": 400,
    "Offline Event": 350,
    Referral: 270,
  },
  salesByModel: {
    "SUV X1": 120,
    "Sedan Y2": 180,
    "Hatchback Z3": 150,
    "Luxury SUV X5": 80,
    "Electric E1": 90,
  },
  revenueByMonth: {
    Jan: 450000000,
    Feb: 480000000,
    Mar: 520000000,
    Apr: 510000000,
    May: 550000000,
    Jun: 600000000,
  },
}

